/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Science;

import Main.Deshbord;
import Main.ScienceHub;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author mmamm
 */
public class AcidOrBase extends javax.swing.JFrame {

    /**
     * Creates new form phSheet
     */
    //complete
    int complete = 0;

    //Score
    int score = 0;

    //Health
    int health = 4;

    //Qustion Change
    int count = 0;

    //SelectedSheet
    String selection = "";

    public AcidOrBase() {
        initComponents();
        btnReattampt.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    String idPas = "";

    public void setId(String id) {
        idPas = id;
        try {
            Connection con = database.db.getConnection();
            String sql = "SELECT userName FROM smart_learning.register WHERE id=?;";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, id);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                String uName = rs.getString("userName");
                lblUname.setText("welcome " + uName);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Deshbord.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Enable() {
        btnBlueLitmusSheet.setEnabled(true);
        btnRedLitmusSheet.setEnabled(true);
    }

    public void Disable() {
        btnBlueLitmusSheet.setEnabled(false);
        btnRedLitmusSheet.setEnabled(false);
    }

    public void Asid() {
        ImageIcon icon = new ImageIcon(AcidOrBase.class.getResource("/Images/Asid sheet.png"));
        lblLitmusSheetSet.setIcon(icon);
    }

    public void Base() {
        ImageIcon icon = new ImageIcon(AcidOrBase.class.getResource("/Images/Base sheet.png"));
        lblLitmusSheetSet.setIcon(icon);
    }

    public void NormalBlue() {
        ImageIcon icon = new ImageIcon(AcidOrBase.class.getResource("/Images/blue Normal Sheet.png"));
        lblLitmusSheetSet.setIcon(icon);
    }

    public void NormalRed() {
        ImageIcon icon = new ImageIcon(AcidOrBase.class.getResource("/Images/red Normal Sheet.png"));
        lblLitmusSheetSet.setIcon(icon);
    }

    public void qustionChange() {
        String[] letters = {"Hcl", "NaOH", "<html> H <sub>2</sub> SO <sub>4</sub> </html>", "<html> HNO <sub>3</sub> </html>", "<html> CH <sub>3</sub> COOH </html>", "<html> H <sub>2</sub> O </html>", "KOH", "<html> NH <sub>4</sub> OH </html>", "NaCl", "<html> Mg(OH) <sub>2</sub>  </html>"};
        lblObject.setText(letters[count]);
    }

    public void setLitmusDetails() {

        //Qustion 1 
        if (lblObject.getText().equals("Hcl")) {
            if (selection.equals("red")) {
                NormalRed();
            } else {
                Asid();
            }

            //Qustion 2    
        } else if (lblObject.getText().equals("NaOH")) {
            if (selection.equals("red")) {
                Base();
            } else {
                NormalBlue();
            }

            //Qustion 3    
        } else if (lblObject.getText().equals("<html> H <sub>2</sub> SO <sub>4</sub> </html>")) {
            if (selection.equals("red")) {
                NormalRed();
            } else {
                Asid();
            }

            //Qustion 4
        } else if (lblObject.getText().equals("<html> HNO <sub>3</sub> </html>")) {
            if (selection.equals("red")) {
                NormalRed();
            } else {
                Asid();
            }

            //Qustion 5
        } else if (lblObject.getText().equals("<html> CH <sub>3</sub> COOH </html>")) {
            if (selection.equals("red")) {
                NormalRed();
            } else {
                Asid();
            }

            //Qustion 6
        } else if (lblObject.getText().equals("<html> H <sub>2</sub> O </html>")) {
            if (selection.equals("red")) {
                NormalRed();
            } else {
                NormalBlue();
            }

            //Qustion 7
        } else if (lblObject.getText().equals("KOH")) {
            if (selection.equals("red")) {
                Base();
            } else {
                NormalBlue();
            }

            //Qustion 8
        } else if (lblObject.getText().equals("<html> NH <sub>4</sub> OH </html>")) {
            if (selection.equals("red")) {
                Base();
            } else {
                NormalBlue();
            }

            //Qustion 9
        } else if (lblObject.getText().equals("NaCl")) {
            if (selection.equals("red")) {
                NormalRed();
            } else {
                NormalBlue();
            }

            //Qustion 10
        } else if (lblObject.getText().equals("<html> Mg(OH) <sub>2</sub>  </html>")) {
            if (selection.equals("red")) {
                Base();
            } else {
                NormalBlue();
            }
        }

    }
    
    public void insertToSql() {
        try {
            // create connection to database
            Connection con = database.db.getConnection();
            // Create prepared statement with the sql query
            PreparedStatement st1 = con.prepareStatement("UPDATE `smart_learning`.`science` SET `BaseOrAsidScore` = ?, `BaseOrAsidComplete` = ? WHERE (`stRegId` = '" + idPas + "');");
            // execute query
            st1.setString(1, score + "");
            st1.setString(2, complete + "");

            st1.executeUpdate();
            lblScore.setText(score + "");

            // show success message
        } catch (SQLException ex) {
            Logger.getLogger(ElectronicConfiguration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Chack() {

        //Qustion 1 
        if (lblObject.getText().equals("Hcl")) {
            if (lblAnswerName.getText().equals("Acid")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);

                }
            }

            //Qustion 2    
        } else if (lblObject.getText().equals("NaOH")) {
            if (lblAnswerName.getText().equals("Base")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }

            //Qustion 3    
        } else if (lblObject.getText().equals("<html> H <sub>2</sub> SO <sub>4</sub> </html>")) {
            if (lblAnswerName.getText().equals("Acid")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }
            //Qustion 4
        } else if (lblObject.getText().equals("<html> HNO <sub>3</sub> </html>")) {
            if (lblAnswerName.getText().equals("Acid")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }

            //Qustion 5
        } else if (lblObject.getText().equals("<html> CH <sub>3</sub> COOH </html>")) {
            if (lblAnswerName.getText().equals("Acid")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }

            //Qustion 6
        } else if (lblObject.getText().equals("<html> H <sub>2</sub> O </html>")) {
            if (lblAnswerName.getText().equals("Normal")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }

            //Qustion 7
        } else if (lblObject.getText().equals("KOH")) {
            if (lblAnswerName.getText().equals("Base")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }

            //Qustion 8
        } else if (lblObject.getText().equals("<html> NH <sub>4</sub> OH </html>")) {
            if (lblAnswerName.getText().equals("Base")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }

            //Qustion 9
        } else if (lblObject.getText().equals("NaCl")) {
            if (lblAnswerName.getText().equals("Normal")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }

            //Qustion 10
        } else if (lblObject.getText().equals("<html> Mg(OH) <sub>2</sub>  </html>")) {
            if (lblAnswerName.getText().equals("Base")) {
                score = score + 10;
                lblScore.setText(score + "");
                lblScoreSide.setText("Score - " + score);

            } else {

                health--;
                if (health == 3) {
                    health4.setVisible(false);
                } else if (health == 2) {
                    health3.setVisible(false);
                } else if (health == 1) {
                    health2.setVisible(false);
                } else if (health == 0) {
                    health1.setVisible(false);

                    btnNext.setEnabled(false);
                    btnChack.setEnabled(false);
                    btnReattampt.setVisible(true);
                }
            }
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        health2 = new javax.swing.JButton();
        health4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        health3 = new javax.swing.JButton();
        health1 = new javax.swing.JButton();
        lblMainObject = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        lblUname = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblUserName9 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        lblComplete = new javax.swing.JLabel();
        lblScoreSide = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblLitmusSheetSet = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRedLitmusSheet = new javax.swing.JButton();
        lblObject = new javax.swing.JLabel();
        btnBlueLitmusSheet = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnNormal = new javax.swing.JButton();
        btnAcid = new javax.swing.JButton();
        btnBase = new javax.swing.JButton();
        lblAnswerName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnReattampt = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnChack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnl_Header.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Health");
        pnl_Header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 194, 20));

        health2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hart.png"))); // NOI18N
        health2.setBorder(null);
        health2.setContentAreaFilled(false);
        pnl_Header.add(health2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, -1));

        health4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hart.png"))); // NOI18N
        health4.setBorder(null);
        health4.setContentAreaFilled(false);
        pnl_Header.add(health4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Set the correct indicator in correct place.");
        pnl_Header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 419, -1));

        health3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hart.png"))); // NOI18N
        health3.setBorder(null);
        health3.setContentAreaFilled(false);
        pnl_Header.add(health3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        health1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hart.png"))); // NOI18N
        health1.setBorder(null);
        health1.setContentAreaFilled(false);
        pnl_Header.add(health1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblMainObject.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lblMainObject.setForeground(new java.awt.Color(51, 51, 51));
        lblMainObject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainObject.setText("Acid or Base ");
        pnl_Header.add(lblMainObject, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 419, -1));

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Score");
        pnl_Header.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        lblScore.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblScore.setForeground(new java.awt.Color(102, 102, 102));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("000");
        pnl_Header.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 39, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/scienceTitle.png"))); // NOI18N
        pnl_Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jButton6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 102));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        lblUname.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        lblUname.setForeground(new java.awt.Color(102, 102, 102));
        lblUname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUname.setText("Wlcome Admin");

        jPanel14.setBackground(new java.awt.Color(247, 247, 247));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.setEnabled(false);

        lblUserName9.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        lblUserName9.setForeground(new java.awt.Color(102, 102, 102));
        lblUserName9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName9.setText("Acid or Base");

        lblComplete.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblComplete.setForeground(new java.awt.Color(102, 102, 102));
        lblComplete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComplete.setText("Completed - 0%");

        lblScoreSide.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblScoreSide.setForeground(new java.awt.Color(102, 102, 102));
        lblScoreSide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreSide.setText("Score - 000");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblScoreSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jSeparator14))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUserName9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblComplete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblScoreSide)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        jButton2.setText("Acid or Base");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUname)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLitmusSheetSet.setForeground(new java.awt.Color(102, 102, 102));
        lblLitmusSheetSet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(lblLitmusSheetSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 40, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cup.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, 200));

        btnRedLitmusSheet.setBackground(new java.awt.Color(255, 102, 102));
        btnRedLitmusSheet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/redSheet.png"))); // NOI18N
        btnRedLitmusSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedLitmusSheetActionPerformed(evt);
            }
        });
        jPanel1.add(btnRedLitmusSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 50, 190));

        lblObject.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lblObject.setForeground(new java.awt.Color(51, 51, 51));
        lblObject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObject.setText("Hcl");
        jPanel1.add(lblObject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 770, 40));

        btnBlueLitmusSheet.setBackground(new java.awt.Color(153, 153, 255));
        btnBlueLitmusSheet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BlueSheet.png"))); // NOI18N
        btnBlueLitmusSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlueLitmusSheetActionPerformed(evt);
            }
        });
        jPanel1.add(btnBlueLitmusSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 50, 190));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" Litmus papers");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 300, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Above Elemet is Acid or Base or Normal ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 350, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Put  litmus paper and test color");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 350, -1));

        btnNormal.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnNormal.setForeground(new java.awt.Color(102, 102, 102));
        btnNormal.setText("Normal");
        btnNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnNormal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });
        jPanel1.add(btnNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 140, 40));

        btnAcid.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnAcid.setForeground(new java.awt.Color(102, 102, 102));
        btnAcid.setText("Acid");
        btnAcid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnAcid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcidActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 140, 40));

        btnBase.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnBase.setForeground(new java.awt.Color(102, 102, 102));
        btnBase.setText("Base");
        btnBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 140, 40));

        lblAnswerName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblAnswerName.setForeground(new java.awt.Color(102, 102, 102));
        lblAnswerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnswerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        lblAnswerName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAnswerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnswerNameMouseClicked(evt);
            }
        });
        jPanel1.add(lblAnswerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 180, 40));

        jButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 90, 30));

        btnNext.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(51, 51, 51));
        btnNext.setText("Next");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 100, 30));

        btnReattampt.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnReattampt.setForeground(new java.awt.Color(51, 51, 51));
        btnReattampt.setText("Reattampt");
        btnReattampt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReattamptActionPerformed(evt);
            }
        });
        jPanel1.add(btnReattampt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 110, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 770, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 303, 770, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 303, 770, 10));

        btnChack.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnChack.setForeground(new java.awt.Color(51, 51, 51));
        btnChack.setText("Chack");
        btnChack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChackActionPerformed(evt);
            }
        });
        jPanel1.add(btnChack, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addComponent(pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        lblAnswerName.setText("");

        String txt = btnNormal.getText();
        lblAnswerName.setText(txt);
        btnNormal.setVisible(false);

        btnAcid.setVisible(true);
        btnBase.setVisible(true);
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnAcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcidActionPerformed
        lblAnswerName.setText("");

        String txt = btnAcid.getText();
        lblAnswerName.setText(txt);
        btnAcid.setVisible(false);

        btnBase.setVisible(true);
        btnNormal.setVisible(true);
    }//GEN-LAST:event_btnAcidActionPerformed

    private void btnBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseActionPerformed
        lblAnswerName.setText("");

        String txt = btnBase.getText();
        lblAnswerName.setText(txt);
        btnBase.setVisible(false);

        btnAcid.setVisible(true);
        btnNormal.setVisible(true);
    }//GEN-LAST:event_btnBaseActionPerformed

    private void lblAnswerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnswerNameMouseClicked
        lblAnswerName.setText("");
        btnAcid.setVisible(true);
        btnBase.setVisible(true);
        btnNormal.setVisible(true);

    }//GEN-LAST:event_lblAnswerNameMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        btnNext.setEnabled(false);
        btnChack.setEnabled(true);

        if (lblObject.getText().equals("<html> Mg(OH) <sub>2</sub>  </html>")) {
            btnNext.setEnabled(false);
            btnNext.setText("Finished");
        } else {
            count++;
            qustionChange();
            lblLitmusSheetSet.setIcon(null);

            lblAnswerName.setText("");

            btnAcid.setVisible(true);
            btnBase.setVisible(true);
            btnNormal.setVisible(true);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnRedLitmusSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedLitmusSheetActionPerformed
        selection = "red";
        setLitmusDetails();
    }//GEN-LAST:event_btnRedLitmusSheetActionPerformed

    private void btnBlueLitmusSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlueLitmusSheetActionPerformed
        selection = "blue";
        setLitmusDetails();
    }//GEN-LAST:event_btnBlueLitmusSheetActionPerformed

    private void btnReattamptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReattamptActionPerformed
        score = 0;
        lblScore.setText(score + "");
        lblScoreSide.setText("Score - " + score);
        complete = 0;
        lblComplete.setText("Completed - " + complete + "%");

        health = 4;
        health1.setVisible(true);
        health2.setVisible(true);
        health3.setVisible(true);
        health4.setVisible(true);

        count = 0;
        qustionChange();
        
        btnChack.setEnabled(true);
        btnReattampt.setVisible(false);
    }//GEN-LAST:event_btnReattamptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ScienceHub sh = new ScienceHub();
        sh.setId(idPas);
        sh.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnChackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChackActionPerformed
        complete = complete + 10;
        lblComplete.setText("Completed - " + complete + "%");
        btnChack.setEnabled(false);
        btnNext.setEnabled(true);
        Chack();
        insertToSql();
    }//GEN-LAST:event_btnChackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcidOrBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcidOrBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcidOrBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcidOrBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcidOrBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcid;
    private javax.swing.JButton btnBase;
    private javax.swing.JButton btnBlueLitmusSheet;
    private javax.swing.JButton btnChack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnReattampt;
    private javax.swing.JButton btnRedLitmusSheet;
    private javax.swing.JButton health1;
    private javax.swing.JButton health2;
    private javax.swing.JButton health3;
    private javax.swing.JButton health4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAnswerName;
    private javax.swing.JLabel lblComplete;
    private javax.swing.JLabel lblLitmusSheetSet;
    private javax.swing.JLabel lblMainObject;
    private javax.swing.JLabel lblObject;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreSide;
    private javax.swing.JLabel lblUname;
    private javax.swing.JLabel lblUserName9;
    private javax.swing.JPanel pnl_Header;
    // End of variables declaration//GEN-END:variables
}
