/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Science.AcidOrBase;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mmamm
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        female();
    }

    String gender = "F";

    public void male() {
        gender = "M";
        ImageIcon icon = new ImageIcon(AcidOrBase.class.getResource("/Images/man AvatarCilected.png"));
        lblMale.setIcon(icon);

        icon = new ImageIcon(AcidOrBase.class.getResource("/Images/woman Avatar mini.png"));
        lblFemale.setIcon(icon);
    }

    public void female() {
        gender = "F";
        ImageIcon icon = new ImageIcon(AcidOrBase.class.getResource("/Images/woman Avatar celected.png"));
        lblFemale.setIcon(icon);

        icon = new ImageIcon(AcidOrBase.class.getResource("/Images/man Avatar mini.png"));
        lblMale.setIcon(icon);
    }

    public void sqlSubject(String uName) {

        String id = "";
        try {
            Connection con = database.db.getConnection();
            String sql = "SELECT id FROM smart_learning.register where userName=? ;";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, uName);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                id = rs.getString("id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            // create connection to database
            Connection con = database.db.getConnection();
            // Create prepared statement with the sql query
            PreparedStatement st1 = con.prepareStatement("INSERT INTO `smart_learning`.`science` (`stRegId`) VALUES (?);");
            PreparedStatement st2 = con.prepareStatement("INSERT INTO `smart_learning`.`ict` (`stRegId`) VALUES (?);");
            PreparedStatement st3 = con.prepareStatement("INSERT INTO `smart_learning`.`maths` (`stRegId`) VALUES (?);");

            st1.setString(1, id);
            st2.setString(1, id);
            st3.setString(1, id);
            // execute query
            st1.executeUpdate();
            st2.executeUpdate();
            st3.executeUpdate();

            // show success message
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMale = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFemale = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtConPassword = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chackBoxAgree = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtCotact = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/man Avatar mini.png"))); // NOI18N
        lblMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaleMouseClicked(evt);
            }
        });
        jPanel1.add(lblMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 60, 60));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("*First Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblFemale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/woman Avatar mini.png"))); // NOI18N
        lblFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFemaleMouseClicked(evt);
            }
        });
        jPanel1.add(lblFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 60, 60));

        txtFirstName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(153, 153, 153));
        txtFirstName.setText("Enter the first name");
        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 273, 35));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("*User Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtUserName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setText("Enter the user name");
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 270, 35));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("*Password :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txtPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("Enter the password");
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 273, 35));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("*Last Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        txtLastName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(153, 153, 153));
        txtLastName.setText("Enter the last name");
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 270, 35));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("*Confirm Password :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        txtConPassword.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtConPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtConPassword.setText("Enter the password");
        txtConPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConPasswordFocusLost(evt);
            }
        });
        jPanel1.add(txtConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 273, 35));

        btnSignup.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(37, 105, 214));
        btnSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup btn.png"))); // NOI18N
        btnSignup.setContentAreaFilled(false);
        btnSignup.setEnabled(false);
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 273, 41));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Have already an account ?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 273, -1));

        lblLogin.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 102, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 273, -1));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 105, 214));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create Account");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 630, -1));

        chackBoxAgree.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        chackBoxAgree.setForeground(new java.awt.Color(102, 102, 102));
        chackBoxAgree.setText("I agree all statments in terms of service");
        chackBoxAgree.setContentAreaFilled(false);
        chackBoxAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chackBoxAgreeActionPerformed(evt);
            }
        });
        jPanel1.add(chackBoxAgree, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Contect");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        txtCotact.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtCotact.setForeground(new java.awt.Color(153, 153, 153));
        txtCotact.setText("Enter the contact");
        txtCotact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCotactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCotactFocusLost(evt);
            }
        });
        jPanel1.add(txtCotact, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 273, 35));

        lblError.setBackground(new java.awt.Color(255, 51, 51));
        lblError.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 560, 20));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Grow with Smart Learning");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 630, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Registation frm.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        Login lg = new Login();
        lg.show();
        this.dispose();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void txtFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusGained
        if (txtFirstName.getText().equals("Enter the first name")) {
            txtFirstName.setText("");
            txtFirstName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFirstNameFocusGained

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        if (txtFirstName.getText().equals("")) {
            txtFirstName.setText("Enter the first name");
            txtFirstName.setForeground(new Color(153, 153, 153));
        } else {
            txtFirstName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusGained
        if (txtLastName.getText().equals("Enter the last name")) {
            txtLastName.setText("");
            txtLastName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtLastNameFocusGained

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        if (txtLastName.getText().equals("")) {
            txtLastName.setText("Enter the last name");
            txtLastName.setForeground(new Color(153, 153, 153));
        } else {
            txtLastName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtLastNameFocusLost

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
        if (txtUserName.getText().equals("Enter the user name")) {
            txtUserName.setText("");
            txtUserName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUserNameFocusGained

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        if (txtUserName.getText().equals("")) {
            txtUserName.setText("Enter the user name");
            txtUserName.setForeground(new Color(153, 153, 153));
        } else {
            txtUserName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUserNameFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (txtPassword.getText().equals("Enter the password")) {
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getText().equals("")) {
            txtPassword.setText("Enter the password");
            txtPassword.setForeground(new Color(153, 153, 153));
        } else {
            txtPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtConPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConPasswordFocusGained
        if (txtConPassword.getText().equals("Enter the password")) {
            txtConPassword.setText("");
            txtConPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtConPasswordFocusGained

    private void txtConPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConPasswordFocusLost
        if (txtConPassword.getText().equals("")) {
            txtConPassword.setText("Enter the password");
            txtConPassword.setForeground(new Color(153, 153, 153));
        } else {
            txtConPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtConPasswordFocusLost

    private void txtCotactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCotactFocusGained
        if (txtCotact.getText().equals("Enter the contact")) {
            txtCotact.setText("");
            txtCotact.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCotactFocusGained

    private void txtCotactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCotactFocusLost
        if (txtCotact.getText().equals("")) {
            txtCotact.setText("Enter the contact");
            txtCotact.setForeground(new Color(153, 153, 153));
        } else {
            txtCotact.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCotactFocusLost

    private void chackBoxAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chackBoxAgreeActionPerformed
        if (chackBoxAgree.isSelected()) {
            btnSignup.setEnabled(true);
        } else {
            btnSignup.setEnabled(false);
        }
    }//GEN-LAST:event_chackBoxAgreeActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed

//get valuse to variable
        String fName = txtFirstName.getText();
        String lName = txtLastName.getText();
        String uName = txtUserName.getText();

        String contact = txtCotact.getText();
        if (contact.equals("Enter the contact")) {
            contact = "";
        }

        String password = txtPassword.getText();
        String conPass = txtConPassword.getText();

//chack epmty field
        if ((fName.equals("") || fName.equals("Enter the first name")) || (lName.equals("") || lName.equals("Enter the last name")) || (password.equals("") || password.equals("Enter the password")) || (conPass.equals("") || conPass.equals("Enter the password"))) {
            lblError.setText("Some fields are empty !");
        } else {
            lblError.setText("");

//chack password and conPass            
            if (password.equals(conPass)) {

//chack user name is used or not
                try {
                    Connection con = database.db.getConnection();
                    String sql = "SELECT userName FROM smart_learning.register WHERE userName=?;";
                    PreparedStatement st = con.prepareStatement(sql);
                    st.setString(1, uName);
                    ResultSet rs = st.executeQuery();
                    if (rs.next()) {

                        lblError.setText(uName + " is alrady excisted !");
//Inset to database                        
                    } else {
                        // Create prepared statement with the sql query
                        PreparedStatement st1 = con.prepareStatement("INSERT INTO `smart_learning`.`register` (`firstName`, `lastName`, `userName`, `password`, `contact`,`Gender`) VALUES (? ,? ,? ,? ,? ,? );");
                        // execute query
                        st1.setString(1, fName);
                        st1.setString(2, lName);
                        st1.setString(3, uName);
                        st1.setString(4, password);
                        st1.setString(5, contact);
                        st1.setString(6, gender);

                        st1.executeUpdate();
                        
// insert id into subject database
                        sqlSubject(uName);
                        // show success message
                        lblError.setForeground(new Color(37, 105, 214));
                        lblError.setText("Succes fully created");

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                lblError.setText("Password and Confirm Password is dosn't match");
            }
        }


    }//GEN-LAST:event_btnSignupActionPerformed

    private void lblFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFemaleMouseClicked
        female();
    }//GEN-LAST:event_lblFemaleMouseClicked

    private void lblMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaleMouseClicked
        male();
    }//GEN-LAST:event_lblMaleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private javax.swing.JCheckBox chackBoxAgree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFemale;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMale;
    private javax.swing.JTextField txtConPassword;
    private javax.swing.JTextField txtCotact;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
